export const CREATE_INNOVATION_TYPE = 'CREATE_INNOVATION_TYPE';
export const CREATE_INNOVATION_TYPE_SUCCESS = 'CREATE_INNOVATION_TYPE_SUCCESS';
export const CREATE_INNOVATION_TYPE_ERROR = 'CREATE_INNOVATION_TYPE_ERROR';

export const GET_ALL_INNOVATION_TYPES = 'GET_ALL_INNOVATION_TYPES';
export const GET_ALL_INNOVATION_TYPES_SUCCESS =
  'GET_ALL_INNOVATION_TYPES_SUCCESS';
export const GET_ALL_INNOVATION_TYPES_ERROR = 'GET_ALL_INNOVATION_TYPES_ERROR';

export const GET_INNOVATION_TYPE = 'GET_INNOVATION_TYPE';

export const UPDATE_INNOVATION_TYPE = 'UPDATE_INNOVATION_TYPE';
export const UPDATE_INNOVATION_TYPE_SUCCESS = 'UPDATE_INNOVATION_TYPE_SUCCESS';
export const UPDATE_INNOVATION_TYPE_ERROR = 'UPDATE_INNOVATION_TYPE_ERROR';

export const DELETE_INNOVATION_TYPE = 'DELETE_INNOVATION_TYPE';
export const DELETE_INNOVATION_TYPE_SUCCESS = 'DELETE_INNOVATION_TYPE_SUCCESS';
export const DELETE_INNOVATION_TYPE_ERROR = 'DELETE_INNOVATION_TYPE_ERROR';
