export const CREATE_PRODUCT_TYPE = 'CREATE_PRODUCT_TYPE';
export const CREATE_PRODUCT_TYPE_SUCCESS = 'CREATE_PRODUCT_TYPE_SUCCESS';
export const CREATE_PRODUCT_TYPE_ERROR = 'CREATE_PRODUCT_TYPE_ERROR';

export const GET_ALL_PRODUCT_TYPES = 'GET_ALL_PRODUCT_TYPES';
export const GET_ALL_PRODUCT_TYPES_SUCCESS = 'GET_ALL_PRODUCT_TYPES_SUCCESS';
export const GET_ALL_PRODUCT_TYPES_ERROR = 'GET_ALL_PRODUCT_TYPES_ERROR';
